WIP: fix the edge cases of venv-update; many tests broken

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -ex
+set -eu
 export TOP=$(readlink -f ${TOP:-.})
 export SITEPACKAGES=${SITEPACKAGES:-.}
 export PROJECT=venv_update
@@ -11,27 +11,7 @@ else
     PYPY=false
 fi
 
-if [ -z "$*" ]; then
-    # default arguments
-    set $TOP/tests $SITEPACKAGES/${PROJECT}.py
-fi
-
-if $PYPY; then
-    # coverage under pypy takes too dang long:
-    #   https://bitbucket.org/pypy/pypy/issue/1871/10x-slower-than-cpython-under-coverage#comment-14404182
-    # Having issues with memory, let's try reducing CPUs by half
-    py.test -n $((NCPU / 3)) "$@"
-else
-    # clean up anything left behind from before:
-    coverage combine --rcfile=$TOP/.coveragerc
-    coverage erase --rcfile=$TOP/.coveragerc
-
-    # See: http://nedbatchelder.com/code/coverage/subprocess.html
-    export COVERAGE_PROCESS_START=$TOP/.coveragerc
-
-    # run the tests!
-    py.test -n $NCPU "$@"
-
+coverage-report() {
     # reporting:
     cd $TOP
     coverage combine
@@ -43,4 +23,33 @@ else
     python ./tests/testing/fix_coverage.py '/site-packages/' $TOP
 
     coverage report --fail-under 95  # FIXME: should be 100
+}
+fail() {
+    if ! $PYPY; then coverage-report; fi
+    echo '[31;1mFAIL[m'
+}
+trap fail ERR
+
+
+if [ -z "$*" ]; then
+    # default arguments
+    set $TOP/tests $SITEPACKAGES/${PROJECT}.py
+fi
+
+set -x
+if $PYPY; then
+    # coverage under pypy takes too dang long:
+    #   https://bitbucket.org/pypy/pypy/issue/1871/10x-slower-than-cpython-under-coverage#comment-14404182
+    # Having issues with memory, let's try reducing CPUs by half
+    py.test -n $((NCPU / 3)) "$@"
+else
+    # clean up anything left behind from before:
+    rm -f $TOP/.coverage $TOP/.coverage.*
+
+    # See: http://nedbatchelder.com/code/coverage/subprocess.html
+    export COVERAGE_PROCESS_START=$TOP/.coveragerc
+
+    # run the tests!
+    py.test -n $NCPU "$@"
+    coverage-report
 fi
